# Generated by Django 5.0.4 on 2025-11-14 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash del archivo', max_length=64)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('zip', 'ZIP'), ('pdf', 'PDF'), ('xlsx', 'Excel')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('report_path', models.CharField(blank=True, help_text='Ruta al reporte de importación', max_length=500)),
                ('uploader_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(db_index=True, help_text="Entidad afectada (ej. 'tax_grades')", max_length=50)),
                ('entity_id', models.CharField(db_index=True, help_text='ID de la entidad afectada', max_length=100)),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('import', 'Importar'), ('export', 'Exportar')], db_index=True, max_length=20)),
                ('before', models.JSONField(blank=True, help_text='Estado anterior (JSON)', null=True)),
                ('after', models.JSONField(blank=True, help_text='Estado posterior (JSON)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='audit_logs_entity_22e216_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_logs_user_id_2252c7_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number_or_page', models.IntegerField(help_text='Número de fila o página del archivo')),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('warning', 'Advertencia')], max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si aplica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='miapp.import')),
            ],
            options={
                'db_table': 'import_records',
                'indexes': [models.Index(fields=['import_id', 'status'], name='import_reco_import__0a1d4d_idx'), models.Index(fields=['rut', 'year'], name='import_reco_rut_119560_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(db_index=True, help_text='RUT/ID del contribuyente', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(db_index=True, help_text='Ejercicio fiscal (2023, 2024, ...)')),
                ('source_type', models.CharField(choices=[('declaracion', 'Declaración'), ('certificado', 'Certificado'), ('manual', 'Manual'), ('calculo', 'Cálculo')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto dividendos u otro valor', max_digits=15)),
                ('factor', models.DecimalField(blank=True, decimal_places=4, help_text='Factor si aplica', max_digits=10, null=True)),
                ('calculation_basis', models.TextField(blank=True, help_text='Descripción / fórmulas usadas')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_grades_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_grades_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_grades',
                'ordering': ['-year', 'rut'],
                'indexes': [models.Index(fields=['rut', 'year'], name='tax_grades_rut_1e268f_idx'), models.Index(fields=['source_type'], name='tax_grades_source__22544c_idx'), models.Index(fields=['status'], name='tax_grades_status_11ea37_idx'), models.Index(fields=['year'], name='tax_grades_year_911e90_idx')],
            },
        ),
    ]
