# Generated by Django 4.2.7 on 2025-12-10 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendMaintainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_mercado', models.CharField(choices=[('acciones', 'Acciones'), ('cfi', 'CFI'), ('fondos_mutuos', 'Fondos Mutuos')], db_index=True, help_text='Tipo de mercado', max_length=20)),
                ('origen_informacion', models.CharField(choices=[('corredora', 'Corredora'), ('sistema', 'Sistema')], db_index=True, help_text='Origen de la información', max_length=20)),
                ('periodo_comercial', models.IntegerField(db_index=True, help_text='Año del periodo comercial')),
                ('instrumento', models.CharField(help_text='Instrumento financiero', max_length=255)),
                ('fecha_pago_dividendo', models.DateField(help_text='Fecha de pago del dividendo')),
                ('descripcion_dividendo', models.TextField(blank=True, help_text='Descripción del dividendo')),
                ('secuencia_evento_capital', models.IntegerField(blank=True, help_text='Secuencia del evento de capital', null=True)),
                ('acogido_isfut_isift', models.CharField(choices=[('isfut', 'ISFUT'), ('isift', 'ISIFT'), ('ninguno', 'Ninguno')], default='ninguno', help_text='Acogido a ISFUT/ISIFT', max_length=10)),
                ('origen', models.CharField(choices=[('corredora', 'Corredora'), ('sistema', 'Sistema')], help_text='Origen (corredora o sistema)', max_length=20)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=6, help_text='Factor de actualización', max_digits=15, null=True)),
                ('factores_8_37', models.JSONField(blank=True, default=dict, help_text='Factores del 8 al 37 con sus nombres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_maintainers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_maintainers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dividend_maintainers',
                'ordering': ['-periodo_comercial', 'instrumento', 'fecha_pago_dividendo'],
                'indexes': [models.Index(fields=['tipo_mercado', 'origen_informacion', 'periodo_comercial'], name='dividend_ma_tipo_me_6d4f9a_idx'), models.Index(fields=['periodo_comercial'], name='dividend_ma_periodo_b9cc23_idx'), models.Index(fields=['tipo_mercado'], name='dividend_ma_tipo_me_4dee6e_idx'), models.Index(fields=['origen_informacion'], name='dividend_ma_origen__0a6e88_idx'), models.Index(fields=['instrumento'], name='dividend_ma_instrum_c77e8d_idx')],
            },
        ),
    ]
