# Generated by Django 4.2.7 on 2025-12-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_dividendmaintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendmaintainer',
            name='dividendo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dividendo', max_digits=15),
        ),
        migrations.AddField(
            model_name='dividendmaintainer',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor histórico', max_digits=15, null=True),
        ),
    ]
