# Generated by Django 4.2.7 on 2025-12-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_dividendmaintainer_dividendo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendmaintainer',
            name='campos_detallados_sii',
            field=models.JSONField(blank=True, default=dict, help_text='29 campos detallados del certificado SII'),
        ),
    ]
