# Generated by Django 4.2.7 on 2025-12-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_dividendmaintainer_campos_detallados_sii'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxgrade',
            name='fuente_ingreso',
            field=models.CharField(choices=[('archivo', 'Archivo de Carga'), ('manual', 'Ingreso Manual'), ('sistema', 'Proveniente del Sistema')], db_index=True, default='manual', help_text='Fuente de ingreso de la calificación', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dividendmaintainer',
            index=models.Index(fields=['periodo_comercial', 'instrumento', 'fecha_pago_dividendo', 'secuencia_evento_capital'], name='dividend_unique_key_idx'),
        ),
        migrations.AddIndex(
            model_name='taxgrade',
            index=models.Index(fields=['fuente_ingreso'], name='tax_grades_fuente__203c9a_idx'),
        ),
    ]
